### ISSUE TITLE
Testar endpoints, criar collections JSON e salvar dentro do repositório do projeto

### ISSUE THREAD

**Issue by igords-goncalves** [igords-goncalves/meu-time#17]
## Descrição

Criar casos de testes e documentação no isominia.

## Features

Planejamento - https://www.notion.so/igords-goncalves/Teste-T-cnico-29cd24c54337419bb4a2caaaec551997

## Tasks

- [x] Agrupar endpoints relacionados juntos
- [x] Estudar o retorno das requisições
- [x] Exportar schema em JSON file e salvar no repositório
- [x] Migrar do Insominia para Postman

**Comment by igords-goncalves** [comment]
[Postman docs](https://learning.postman.com/docs/getting-started/importing-and-exporting/importing-from-insomnia/)

**Comment by igords-goncalves** [comment]
Documentação da API finalizada, incrementar com mais chamadas futuramente.
