### ISSUE TITLE
Criação do projeto e repositório

### ISSUE THREAD

**Issue by igords-goncalves** [igords-goncalves/meu-time#3]
## Descrição 

Criação do projeto inicial, criação do repositório no github e configuração do projeto.

## Features

~~~~
yarn create vite . --template typescript
~~~~

## Tasks

- [x] Criar projeto com vite + yarn.
- [x] Utilização do TypeScript.
- [x] Criação de novas branchs.
- [x] Configuração do projeto com linters e padronizadores.
- [x] Instalação de pacotes e dependências.

**Comment by igords-goncalves** [comment]
Reabrindo para adicionar mais configurações de ambiente.
