### ISSUE TITLE
US#5 - Tela de Login

### ISSUE THREAD

**Issue by igords-goncalves** [igords-goncalves/meu-time#5]
## Descrição

Criar a tela de login conforme proposto em protótipo

## Features

Planejamento - https://www.notion.so/igords-goncalves/Teste-T-cnico-29cd24c54337419bb4a2caaaec551997

## Tasks

- [ ] Criar estruturas de pastas
- [ ] Criar componente de layout
- [ ] Criar componentes de template
- [ ] Criar componentes genéricos/comuns
- [ ] Criar hook para chamada de API
- [ ] Criar .env p/ para aramzenar URL e chave de acesso
- [ ] Criar instância do axios
- [ ] Criar tela para redirecionamento após login

## Protótipo

![Image](https://user-images.githubusercontent.com/79734585/239246725-c91b334e-ec82-4809-8861-b5c454076bdf.png)

**Comment by igords-goncalves** [comment]
Não será viável armazenar a chave de acesso, embora seja um meio inseguro deixar a mesma como pública.
