### ISSUE TITLE
TSK - Criar rotas de navegação

### ISSUE THREAD

**Issue by igords-goncalves** [igords-goncalves/meu-time#8]
## Descrição

Criar componente de navegação com react router dom .

## Features

Planejamento - https://www.notion.so/igords-goncalves/Teste-T-cnico-29cd24c54337419bb4a2caaaec551997

## Tasks

- [ ] Criar componente principal em routes
- [ ] Criar router de navegação em App.js
- [ ] Criar endpoints de navegação

**Comment by igords-goncalves** [comment]
Essa funcionalidade já foi implementada.

````js
export const ROUTES = [
  { path: '/', component: Login },
  { path: '/home', component: Home },
  { path: '/dashboard', component: Dashboard },
];
````
